# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_O_7U_LURPm-90ICmJgizc7EbslfnUmI
"""



"""# Task
Perform exploratory data analysis on the iris dataset located at "/content/iris.data". Load the dataset with Pandas, generate summary statistics, create visualizations (histograms, scatter plots, box plots) for each feature, analyze correlations among features, and summarize key findings in a brief report.

## Load the dataset

### Subtask:
Load the iris dataset from `/content/iris.data` into a pandas DataFrame.

**Reasoning**:
The first step is to load the dataset into a pandas DataFrame according to the instructions.
"""

import pandas as pd

# Load the dataset, specifying no header
df = pd.read_csv('/content/iris.data', header=None)

# Assign column names
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

# Display the first few rows
display(df.head())

"""## Generate summary statistics

### Subtask:
Calculate and display summary statistics for each feature in the dataset.

**Reasoning**:
Calculate and display summary statistics for numerical features and the distribution of the 'class' column.
"""

# Calculate and display summary statistics for numerical columns
display(df.describe())

# Calculate and display the distribution of the 'class' column
display(df['class'].value_counts())

"""## Create visualizations

### Subtask:
Generate visualizations (e.g., histograms, scatter plots, box plots) to explore the distribution and relationships of each feature.

**Reasoning**:
Generate visualizations (histograms, scatter plots, box plots) to explore the distribution and relationships of each feature.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set_style("whitegrid")

# 1. Create histograms for each numerical feature
numerical_features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df[numerical_features].hist(bins=15, figsize=(12, 8), layout=(2, 2))
plt.suptitle('Histograms of Iris Features', y=1.02, fontsize=16)
plt.tight_layout()
plt.show()

# 2. Generate scatter plots for pairs of numerical features
sns.pairplot(df, hue='class', diag_kind='kde')
plt.suptitle('Scatter Plots of Iris Features by Class', y=1.02, fontsize=16)
plt.show()

# 3. Create box plots for each numerical feature, grouped by class
plt.figure(figsize=(12, 8))
for i, feature in enumerate(numerical_features):
    plt.subplot(2, 2, i + 1)
    sns.boxplot(x='class', y=feature, data=df)
    plt.title(f'Box Plot of {feature} by Class')
plt.tight_layout()
plt.show()

"""## Analyze correlations

### Subtask:
Calculate and visualize the correlation matrix to understand the relationships between different features.

**Reasoning**:
Calculate and visualize the correlation matrix of the numerical features using a heatmap.
"""

# Select numerical columns
numerical_df = df.select_dtypes(include=['float64', 'int64'])

# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()

# Create a heatmap of the correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Iris Features')
plt.show()

"""## Summarize key findings

### Subtask:
Summarize the key insights and patterns observed during the exploratory data analysis.

**Reasoning**:
Summarize the key findings from the EDA steps.
"""

print("Key Findings from Iris Dataset EDA:")
print("\nSummary Statistics:")
print("- The dataset contains 150 instances with 4 numerical features and 1 categorical class label.")
print("- Each of the three classes (Iris-setosa, Iris-versicolor, Iris-virginica) has 50 instances, indicating a balanced dataset.")
print("- Petal length and petal width have wider ranges and higher standard deviations compared to sepal length and sepal width, suggesting more variability in these features.")

print("\nVisualizations:")
print("- Histograms show that sepal width has a roughly normal distribution, while sepal length, petal length, and petal width appear to be multimodal or skewed.")
print("- Scatter plots reveal clear separation between Iris-setosa and the other two classes based on petal length and petal width. Iris-versicolor and Iris-virginica show some overlap, but are generally distinguishable, especially using petal features.")
print("- Box plots further highlight the separation of classes based on feature distributions. Iris-setosa has significantly smaller petal lengths and widths than the other two classes.")

print("\nCorrelation Analysis:")
print("- There are strong positive correlations between petal length and petal width (~0.96).")
print("- Strong positive correlations also exist between sepal length and petal length (~0.87), and sepal length and petal width (~0.82).")
print("- Sepal width shows weak or negative correlations with the other features.")
print("- The high correlations among petal dimensions and between sepal length and petal dimensions suggest that these features are highly related and contribute significantly to distinguishing the different Iris species.")

"""## Summary:

### Data Analysis Key Findings

*   The dataset is balanced, with 50 instances for each of the three Iris classes (Iris-setosa, Iris-versicolor, and Iris-virginica).
*   Petal length and petal width exhibit greater variability (wider ranges and higher standard deviations) compared to sepal length and sepal width.
*   Histograms suggest varying distributions for features, with sepal width appearing roughly normal and others potentially multimodal or skewed.
*   Visualizations clearly demonstrate that Iris-setosa is well-separated from Iris-versicolor and Iris-virginica, particularly based on petal dimensions.
*   Iris-versicolor and Iris-virginica show some overlap but are generally distinguishable, especially when considering petal length and width.
*   There is a very strong positive correlation between petal length and petal width (~0.96).
*   Strong positive correlations are also observed between sepal length and petal length (~0.87), and between sepal length and petal width (~0.82).
*   Sepal width shows weak or negative correlations with the other features.

### Insights or Next Steps

*   The strong correlations among petal features suggest that these are the most discriminative features for separating Iris species. Sepal width appears to be less informative on its own.
*   Future analysis or modeling efforts should leverage petal length and petal width, and potentially sepal length, as they are key in differentiating the classes. The distinct separation of Iris-setosa implies a simpler classification rule for this class.

"""